# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=255)),
                ('killed', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('uninsured', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
