# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_api', '0003_auto_20170527_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rep',
            name='freedom_caucus_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rep',
            name='medicaid_expansion_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='percent_vote_2016',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rep',
            name='percent_vote_clinton',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rep',
            name='percent_vote_trump',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rep',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rep',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rep',
            name='president_vote_margin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rep',
            name='swing_left_district',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rep',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
