# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_api', '0004_auto_20170529_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='pre_exist_premium',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
